




name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📂 Sync Files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "**"
          target: "/var/www/html/cartorio360/public_html/producao/web_service_360"
          rm: true
          
          

      - name: 📂 Create .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22

          script: |
            cd /var/www/html/cartorio360/public_html/producao/web_service_360
            touch .env
            
            echo "MS_MANAGEMENT_PORT=${{secrets.MS_MANAGEMENT_PORT}}" | tee -a .env
            echo "MS_MANAGEMENT_PORT: ${{secrets.MS_MANAGEMENT_PORT}}" | tee -a .env
            echo "DB_POSTGRES_HOST: ${{secrets.DB_POSTGRES_HOST}}" | tee -a .env
            echo "DB_POSTGRES_PORT: ${{secrets.DB_POSTGRES_PORT}}" | tee -a .env
            echo "DB_POSTGRES_USER: ${{secrets.DB_POSTGRES_USER}}" | tee -a .env
            echo "DB_POSTGRES_PASS: ${{secrets.DB_POSTGRES_PASS}}" | tee -a .env
            echo "DB_POSTGRES_DATABASE: ${{secrets.DB_POSTGRES_DATABASE}}" | tee -a .env
            echo "DURABIL_DB_POSTGRES_DATABASE: ${{secrets.DURABIL_DB_POSTGRES_DATABASE}}" | tee -a .env
            echo "MINIO_ENDPOINT: ${{secrets.MINIO_ENDPOINT}}" | tee -a .env
            echo "MINIO_API_PORT: ${{secrets.MINIO_API_PORT}}" | tee -a .env
            echo "MINIO_ACCESS_KEY: ${{secrets.MINIO_ACCESS_KEY}}" | tee -a .env
            echo "MINIO_SECRET_KEY: ${{secrets.MINIO_SECRET_KEY}}" | tee -a .env
            echo "SSLCertificateKeyFile: ${{secrets.SSLCertificateKeyFile}}" | tee -a .env
            echo "SSLCertificateFile: ${{secrets.SSLCertificateFile}}" | tee -a .env
            echo "PROJECT: ${{secrets.PROJECT}}" | tee -a .env

      - name: Subindo servidor pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22

          script: |
            cd /var/www/html/cartorio360/public_html/producao/web_service_360
            npm install
            npm run pm2-stop
            npm run pm2
            # docker compose build --no-cache app
            # docker compose up -d app
      - name: Debug    
        run: |

          echo "DEBUG=true" >> $GITHUB_ENV

          echo "DOCKER_LOGS=true" >> $GITHUB_ENV
          
         

