




name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📂 Sync Files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "**"
          target: "/var/www/html/cartorio360/public_html/producao/web_service_360"
          rm: true
          
          

      - name: 📂 Create .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22

          script: |
            cd /var/www/html/cartorio360/public_html/producao/web_service_360
            touch .env

            
            echo "MS_MANAGEMENT_PORT=${{secrets.MS_MANAGEMENT_PORT}}" | tee -a .env
            echo "TJ_PRODUCTION=${{secrets.TJ_PRODUCTION}}" | tee -a .env
            echo "TJ_DESENV=${{secrets.TJ_DESENV}}" | tee -a .env
            echo "NODE_ENV=${{secrets.NODE_ENV}}" | tee -a .env
            echo "SSLCertificateKeyFile: ${{secrets.SSLCertificateKeyFile}}" | tee -a .env
            echo "SSLCertificateFile: ${{secrets.SSLCertificateFile}}" | tee -a .env
            echo "PROJECT: ${{secrets.PROJECT}}" | tee -a .env

      - name: Subindo servidor pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22

          script: |
            cd /var/www/html/cartorio360/public_html/producao/web_service_360
            npm install
            npm run pm2-stop
            npm run pm2
            # docker compose build --no-cache app
            # docker compose up -d app
      - name: Debug    
        run: |

          echo "DEBUG=true" >> $GITHUB_ENV

          echo "DOCKER_LOGS=true" >> $GITHUB_ENV
          
         

